"""
train_model.py  (v4 - production-audit hardened)

Trains a Linear Regression model predicting time_to_full_hours, matching
the architecture diagram's spec. Time-based train/test split throughout
(never random shuffle - this is time-series data).

Audit fixes in this version:
  - Outlier clipping applied to fill_rate_per_hour before training (was
    letting reset-event artifacts as extreme as -198%/hr distort the fit)
  - Model saved as a FeatureContract bundle (model + its exact feature
    list together) so serving code can never silently mismatch features
  - 3-way time split (train/val/test): validation set used for the
    baseline-vs-extended feature comparison, held-out test set used ONLY
    for final reported metrics. Previously the same "test" set was used
    for both model selection AND final reporting, which is a mild form
    of leakage that optimistically biases the reported score.

Run: python train_model.py
Output: time_to_full_model.pkl (a FeatureContract), model_v{N}.pkl (versioned copy)
"""

import pandas as pd
import numpy as np
import json
import os
from datetime import datetime, timezone
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib

from features import FEATURE_COLUMNS, FEATURE_COLUMNS_V2, clip_fill_rate, FeatureContract

TRAIN_FRACTION = 0.7
VAL_FRACTION = 0.15
# remaining 0.15 is test


def next_version_number(pattern="model_v{}.pkl"):
    v = 1
    while os.path.exists(pattern.format(v)):
        v += 1
    return v


def three_way_time_split(df, train_frac=TRAIN_FRACTION, val_frac=VAL_FRACTION):
    """
    Splits by TIME, not randomly - always the correct approach for
    time-series data, since a random shuffle would leak future information
    into training (the model would see rows chronologically "after" its
    test set during training, which never happens in real deployment).
    """
    df = df.sort_values("timestamp_dt").reset_index(drop=True)
    n = len(df)
    train_end = int(n * train_frac)
    val_end = int(n * (train_frac + val_frac))
    return df.iloc[:train_end], df.iloc[train_end:val_end], df.iloc[val_end:]


def evaluate(model, X, y, label):
    preds = model.predict(X)
    mae = mean_absolute_error(y, preds)
    rmse = mean_squared_error(y, preds) ** 0.5
    r2 = r2_score(y, preds)
    print(f"  [{label}] MAE={mae:.2f} hrs  RMSE={rmse:.2f} hrs  R2={r2:.3f}")
    return {"mae_hours": round(mae, 3), "rmse_hours": round(rmse, 3), "r2": round(r2, 3)}


def main():
    df = pd.read_csv("training_dataset.csv")
    df["timestamp_dt"] = pd.to_datetime(df["timestamp"])

    if "is_censored" not in df.columns:
        raise ValueError(
            "training_dataset.csv has no 'is_censored' column - it was likely generated by an "
            "older version of generate_synthetic_data.py. Re-run data generation first."
        )

    # --- Audit fix (censored-label bias): rows where the 90% event never
    # happened within the recorded window have a CAPPED, right-censored
    # label - it's a lower bound on the true time-to-full, not the true
    # value. Training on these as if they were exact labels systematically
    # biases the model toward UNDER-predicting time-to-full for exactly
    # the bins that take longest to fill (the ones most often censored).
    # Fix: fit and report primary metrics on exact-labeled rows only.
    # Censored rows stay in the CSV (so nothing is silently thrown away)
    # and get their own separate, clearly-labeled metric for transparency.
    n_censored_total = df["is_censored"].sum()
    print(f"Dataset: {len(df)} total rows, {n_censored_total} censored ({100*n_censored_total/len(df):.1f}%) - "
          f"excluded from training/primary metrics, evaluated separately below")

    # --- Outlier clip on fill_rate_per_hour (reset-event artifacts) ---
    n_before = len(df)
    outlier_mask = (df["fill_rate_per_hour"] < -20) | (df["fill_rate_per_hour"] > 50)
    n_outliers = outlier_mask.sum()
    df.loc[outlier_mask, "fill_rate_per_hour"] = 0.0
    print(f"Clipped {n_outliers}/{n_before} rows with implausible fill_rate_per_hour (reset-event artifacts)")

    # Time-based split happens on the FULL chronological set (censored rows
    # included) so time boundaries reflect the real timeline. Filtering to
    # exact-only happens per-split, after the split, not before - splitting
    # only on pre-filtered exact rows would shift train/val/test time
    # boundaries in a way that no longer matches the true timeline.
    train_df, val_df, test_df = three_way_time_split(df)
    train_exact = train_df[~train_df["is_censored"]]
    val_exact = val_df[~val_df["is_censored"]]
    test_exact = test_df[~test_df["is_censored"]]
    print(f"Train rows: {len(train_df)} ({len(train_exact)} exact-labeled, used for fitting)")
    print(f"Val rows:   {len(val_df)} ({len(val_exact)} exact-labeled, used for model selection)")
    print(f"Test rows:  {len(test_df)} ({len(test_exact)} exact-labeled, used for final reported metrics)")

    if len(train_exact) < 50:
        raise ValueError(
            f"Only {len(train_exact)} exact-labeled training rows available - too few to fit "
            f"a reliable model. Check OVERFLOW_THRESHOLD / recording window length in "
            f"generate_synthetic_data.py, or the ratio of censored to exact rows."
        )

    results = {}
    for label, cols in [("BASELINE", FEATURE_COLUMNS), ("EXTENDED", FEATURE_COLUMNS_V2)]:
        model = LinearRegression()
        model.fit(train_exact[cols], train_exact["time_to_full_hours"])
        print(f"\n{label} (features={cols})")
        val_metrics = evaluate(model, val_exact[cols], val_exact["time_to_full_hours"], "validation (exact-labeled only)")
        results[label] = {"model": model, "cols": cols, "val_metrics": val_metrics}

    winner_label = "EXTENDED" if results["EXTENDED"]["val_metrics"]["r2"] > results["BASELINE"]["val_metrics"]["r2"] else "BASELINE"
    print(f"\n{'='*60}")
    print(f"Winner (chosen on VALIDATION set, exact-labeled rows only): {winner_label}")
    winner = results[winner_label]

    print(f"\nFinal, held-out TEST set evaluation for {winner_label} (exact-labeled rows only, first time touched):")
    test_metrics = evaluate(winner["model"], test_exact[winner["cols"]], test_exact["time_to_full_hours"], "test (held-out, exact-labeled)")

    # Separate, clearly-labeled diagnostic on censored rows: NOT a fair
    # accuracy metric (their "truth" is a lower bound), but useful to see
    # whether the model's predictions are at least directionally consistent
    # (predictions should generally exceed the censored lower-bound label).
    test_censored = test_df[test_df["is_censored"]]
    censored_diag = None
    if len(test_censored) > 0:
        censored_preds = winner["model"].predict(test_censored[winner["cols"]])
        pct_below_lower_bound = float((censored_preds < test_censored["time_to_full_hours"].values).mean() * 100)
        censored_diag = {
            "n_censored_test_rows": int(len(test_censored)),
            "pct_predictions_below_censored_lower_bound": round(pct_below_lower_bound, 1),
            "note": "This is NOT an accuracy metric (censored labels are a lower bound, not "
                    "ground truth). A prediction below the lower-bound label is a clear sign of "
                    "under-prediction; a low percentage here is reassuring, a high one is a red flag.",
        }
        print(f"  [diagnostic] {len(test_censored)} censored test rows: "
              f"{pct_below_lower_bound:.1f}% of predictions fall BELOW their own lower-bound label "
              f"(should generally be low - flags under-prediction if high)")
    print(f"{'='*60}")

    for feat, coef in zip(winner["cols"], winner["model"].coef_):
        print(f"    {feat}: {coef:.4f}")
    print(f"    intercept: {winner['model'].intercept_:.4f}")

    # --- Audit fix: save model bundled with its feature list, never separately ---
    bundle = FeatureContract(model=winner["model"], feature_columns=winner["cols"])
    version = next_version_number()
    model_filename = f"model_v{version}.pkl"
    joblib.dump(bundle, model_filename)
    joblib.dump(bundle, "time_to_full_model.pkl")

    metadata = {
        "version": version,
        "filename": model_filename,
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "trained_on": "training_dataset.csv",
        "data_source": "simulated",
        "n_train_rows_total": len(train_df),
        "n_train_rows_exact_used_for_fitting": len(train_exact),
        "n_val_rows_total": len(val_df),
        "n_val_rows_exact": len(val_exact),
        "n_test_rows_total": len(test_df),
        "n_test_rows_exact": len(test_exact),
        "n_censored_total": int(n_censored_total),
        "pct_censored_total": round(100 * n_censored_total / len(df), 1),
        "outliers_clipped": int(n_outliers),
        "features": winner["cols"],
        "feature_set_label": winner_label,
        "validation_metrics_exact_only": winner["val_metrics"],
        "test_metrics_exact_only_final_honest_estimate": test_metrics,
        "censored_diagnostic_not_an_accuracy_metric": censored_diag,
        "baseline_val_metrics": results["BASELINE"]["val_metrics"],
        "extended_val_metrics": results["EXTENDED"]["val_metrics"],
        "coefficients": {feat: round(float(c), 4) for feat, c in zip(winner["cols"], winner["model"].coef_)},
        "intercept": round(float(winner["model"].intercept_), 4),
        "known_limitations": [
            f"{100*n_censored_total/len(df):.0f}% of rows are right-censored (the bin never reached "
            f"90% fill within the recorded window) - these are KEPT in training_dataset.csv with an "
            f"is_censored flag and a capped (lower-bound) label, but EXCLUDED from model fitting and "
            f"from the primary reported MAE/RMSE/R2, since training or scoring against a known-wrong "
            f"lower bound would bias both the model and the metrics. See "
            f"'censored_diagnostic_not_an_accuracy_metric' for a directional sanity check on those rows instead.",
            "Linear Regression cannot represent the sawtooth reset pattern "
            "in bin fill data; R2 will remain modest regardless of feature "
            "tuning. This matches the team's own risk-mitigation plan, which "
            "explicitly names a simpler extrapolation fallback for this case.",
            "hour/day_of_week are encoded as raw integers, not cyclically "
            "(e.g. hour 23 and hour 0 are treated as maximally different). "
            "Not fixed here since it likely has small effect vs. the two "
            "issues above, and a hackathon-scope linear model has limited "
            "room to benefit from it regardless.",
            "Trained entirely on simulated data. Retrain on real bin_readings "
            "as soon as it's available - simulated fill-rate patterns are a "
            "guess, not a validated match to real bin behavior.",
        ],
    }
    meta_path = "model_registry.json"
    registry = json.load(open(meta_path)) if os.path.exists(meta_path) else []
    registry.append(metadata)
    with open(meta_path, "w") as f:
        json.dump(registry, f, indent=2)

    print(f"\nSaved: {model_filename}, time_to_full_model.pkl (both are FeatureContract bundles)")
    print(f"Logged to {meta_path} - {len(registry)} version(s) recorded so far")


if __name__ == "__main__":
    main()
